# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_serial.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gadget(object):
    def setupUi(self, Gadget):
        Gadget.setObjectName("Gadget")
        Gadget.resize(900, 555)
        Gadget.setMinimumSize(QtCore.QSize(881, 555))
        Gadget.setMaximumSize(QtCore.QSize(900, 560))
        self.gridLayout = QtWidgets.QGridLayout(Gadget)
        self.gridLayout.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Gadget)
        self.tabWidget.setMaximumSize(QtCore.QSize(880, 555))
        self.tabWidget.setObjectName("tabWidget")
        self.port_tab = QtWidgets.QWidget()
        self.port_tab.setObjectName("port_tab")
        self.formGroupBox = QtWidgets.QGroupBox(self.port_tab)
        self.formGroupBox.setGeometry(QtCore.QRect(680, 360, 191, 91))
        self.formGroupBox.setObjectName("formGroupBox")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setGeometry(QtCore.QRect(13, 34, 81, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setGeometry(QtCore.QRect(13, 60, 81, 18))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 87, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 60, 87, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formGroupBox1 = QtWidgets.QGroupBox(self.port_tab)
        self.formGroupBox1.setGeometry(QtCore.QRect(670, 20, 201, 311))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_1.setGeometry(QtCore.QRect(13, 34, 71, 18))
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox1)
        self.s1__box_1.setGeometry(QtCore.QRect(83, 34, 111, 19))
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_2.setGeometry(QtCore.QRect(13, 63, 60, 18))
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_2.setGeometry(QtCore.QRect(83, 63, 111, 20))
        self.s1__box_2.setObjectName("s1__box_2")
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_3.setGeometry(QtCore.QRect(13, 121, 61, 18))
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_3.setGeometry(QtCore.QRect(83, 121, 91, 20))
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_4.setGeometry(QtCore.QRect(13, 151, 61, 18))
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_4.setGeometry(QtCore.QRect(83, 151, 91, 19))
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_5.setGeometry(QtCore.QRect(13, 180, 61, 18))
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_5.setGeometry(QtCore.QRect(83, 180, 91, 20))
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.open_button = QtWidgets.QPushButton(self.formGroupBox1)
        self.open_button.setGeometry(QtCore.QRect(13, 239, 161, 20))
        self.open_button.setObjectName("open_button")
        self.close_button = QtWidgets.QPushButton(self.formGroupBox1)
        self.close_button.setGeometry(QtCore.QRect(13, 269, 161, 19))
        self.close_button.setObjectName("close_button")
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_6.setGeometry(QtCore.QRect(13, 210, 48, 18))
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_6.setGeometry(QtCore.QRect(83, 210, 91, 20))
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.state_label = QtWidgets.QLabel(self.formGroupBox1)
        self.state_label.setGeometry(QtCore.QRect(13, 93, 151, 18))
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.port_tab)
        self.verticalGroupBox.setGeometry(QtCore.QRect(10, 0, 561, 331))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setGeometry(QtCore.QRect(13, 34, 541, 291))
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.port_tab)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(10, 330, 561, 111))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        self.s3__send_text.setGeometry(QtCore.QRect(13, 34, 541, 64))
        self.s3__send_text.setObjectName("s3__send_text")
        self.layoutWidget = QtWidgets.QWidget(self.port_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 451, 300, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timer_send_cb = QtWidgets.QCheckBox(self.layoutWidget)
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.horizontalLayout.addWidget(self.timer_send_cb)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.dw = QtWidgets.QLabel(self.layoutWidget)
        self.dw.setObjectName("dw")
        self.horizontalLayout.addWidget(self.dw)
        self.layoutWidget1 = QtWidgets.QWidget(self.port_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(572, 52, 95, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hex_receive = QtWidgets.QCheckBox(self.layoutWidget1)
        self.hex_receive.setObjectName("hex_receive")
        self.verticalLayout.addWidget(self.hex_receive)
        self.s2__clear_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.verticalLayout.addWidget(self.s2__clear_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.port_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(571, 361, 96, 90))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hex_send = QtWidgets.QCheckBox(self.layoutWidget2)
        self.hex_send.setObjectName("hex_send")
        self.verticalLayout_2.addWidget(self.hex_send)
        self.s3__send_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.s3__send_button.setObjectName("s3__send_button")
        self.verticalLayout_2.addWidget(self.s3__send_button)
        self.s3__clear_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.verticalLayout_2.addWidget(self.s3__clear_button)
        self.tabWidget.addTab(self.port_tab, "")
        self.net_tab = QtWidgets.QWidget()
        self.net_tab.setObjectName("net_tab")
        self.tabWidget.addTab(self.net_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Gadget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gadget)

    def retranslateUi(self, Gadget):
        _translate = QtCore.QCoreApplication.translate
        Gadget.setWindowTitle(_translate("Gadget", "Form"))
        self.formGroupBox.setTitle(_translate("Gadget", "Port State"))
        self.label.setText(_translate("Gadget", "Recv Length:"))
        self.label_2.setText(_translate("Gadget", "Send Length:"))
        self.formGroupBox1.setTitle(_translate("Gadget", "Port Setting"))
        self.s1__lb_1.setText(_translate("Gadget", "Detection:"))
        self.s1__box_1.setText(_translate("Gadget", "Detection Port"))
        self.s1__lb_2.setText(_translate("Gadget", "Select:"))
        self.s1__lb_3.setText(_translate("Gadget", "Boud Rate:"))
        self.s1__box_3.setItemText(0, _translate("Gadget", "115200"))
        self.s1__box_3.setItemText(1, _translate("Gadget", "2400"))
        self.s1__box_3.setItemText(2, _translate("Gadget", "4800"))
        self.s1__box_3.setItemText(3, _translate("Gadget", "9600"))
        self.s1__box_3.setItemText(4, _translate("Gadget", "14400"))
        self.s1__box_3.setItemText(5, _translate("Gadget", "19200"))
        self.s1__box_3.setItemText(6, _translate("Gadget", "38400"))
        self.s1__box_3.setItemText(7, _translate("Gadget", "57600"))
        self.s1__box_3.setItemText(8, _translate("Gadget", "76800"))
        self.s1__box_3.setItemText(9, _translate("Gadget", "12800"))
        self.s1__box_3.setItemText(10, _translate("Gadget", "230400"))
        self.s1__box_3.setItemText(11, _translate("Gadget", "460800"))
        self.s1__box_3.setItemText(12, _translate("Gadget", "3000000"))
        self.s1__lb_4.setText(_translate("Gadget", "Data Bit:"))
        self.s1__box_4.setItemText(0, _translate("Gadget", "8"))
        self.s1__box_4.setItemText(1, _translate("Gadget", "7"))
        self.s1__box_4.setItemText(2, _translate("Gadget", "6"))
        self.s1__box_4.setItemText(3, _translate("Gadget", "5"))
        self.s1__lb_5.setText(_translate("Gadget", "Check Bit:"))
        self.s1__box_5.setItemText(0, _translate("Gadget", "N"))
        self.open_button.setText(_translate("Gadget", "Open"))
        self.close_button.setText(_translate("Gadget", "Close"))
        self.s1__lb_6.setText(_translate("Gadget", "Stop Bit:"))
        self.s1__box_6.setItemText(0, _translate("Gadget", "1"))
        self.verticalGroupBox.setTitle(_translate("Gadget", "Receiving Area:"))
        self.verticalGroupBox_2.setTitle(_translate("Gadget", "Sending Area:"))
        self.s3__send_text.setHtml(_translate("Gadget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.timer_send_cb.setText(_translate("Gadget", "Timed transmission"))
        self.lineEdit_3.setText(_translate("Gadget", "1000"))
        self.dw.setText(_translate("Gadget", "ms/times"))
        self.hex_receive.setText(_translate("Gadget", "Hex Recv"))
        self.s2__clear_button.setText(_translate("Gadget", "Clean"))
        self.hex_send.setText(_translate("Gadget", "Hex Send"))
        self.s3__send_button.setText(_translate("Gadget", "Send Data"))
        self.s3__clear_button.setText(_translate("Gadget", "Clean"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.port_tab), _translate("Gadget", "Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.net_tab), _translate("Gadget", "Net"))

