# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gadget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gadget(object):
    def setupUi(self, Gadget):
        Gadget.setObjectName("Gadget")
        Gadget.resize(760, 441)
        Gadget.setMinimumSize(QtCore.QSize(760, 440))
        Gadget.setMaximumSize(QtCore.QSize(760, 441))
        self.gridLayout_6 = QtWidgets.QGridLayout(Gadget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(Gadget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.stackedWidgetPage1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formGroupBox1 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.formGroupBox1.setMinimumSize(QtCore.QSize(250, 200))
        self.formGroupBox1.setMaximumSize(QtCore.QSize(250, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.formGroupBox1.setFont(font)
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_1.setGeometry(QtCore.QRect(11, 25, 100, 20))
        self.s1__lb_1.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_1.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_1.setFont(font)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox1)
        self.s1__box_1.setGeometry(QtCore.QRect(118, 25, 120, 20))
        self.s1__box_1.setMinimumSize(QtCore.QSize(120, 20))
        self.s1__box_1.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.s1__box_1.setFont(font)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_2.setGeometry(QtCore.QRect(11, 47, 100, 20))
        self.s1__lb_2.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_2.setFont(font)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_2.setGeometry(QtCore.QRect(118, 47, 120, 20))
        self.s1__box_2.setMinimumSize(QtCore.QSize(120, 20))
        self.s1__box_2.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.s1__box_2.setFont(font)
        self.s1__box_2.setObjectName("s1__box_2")
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_3.setGeometry(QtCore.QRect(11, 89, 100, 20))
        self.s1__lb_3.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_3.setFont(font)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_3.setGeometry(QtCore.QRect(118, 89, 100, 20))
        self.s1__box_3.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__box_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__box_3.setFont(font)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_4.setGeometry(QtCore.QRect(11, 110, 100, 20))
        self.s1__lb_4.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_4.setFont(font)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_4.setGeometry(QtCore.QRect(118, 110, 100, 20))
        self.s1__box_4.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__box_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__box_4.setFont(font)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_5.setGeometry(QtCore.QRect(11, 132, 100, 20))
        self.s1__lb_5.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_5.setFont(font)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_5.setGeometry(QtCore.QRect(118, 132, 100, 20))
        self.s1__box_5.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__box_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__box_5.setFont(font)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.s1__box_5.addItem("")
        self.s1__box_5.addItem("")
        self.s1__box_5.addItem("")
        self.s1__box_5.addItem("")
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox1)
        self.s1__lb_6.setGeometry(QtCore.QRect(11, 153, 100, 20))
        self.s1__lb_6.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__lb_6.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__lb_6.setFont(font)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox1)
        self.s1__box_6.setGeometry(QtCore.QRect(118, 153, 100, 20))
        self.s1__box_6.setMinimumSize(QtCore.QSize(100, 20))
        self.s1__box_6.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.s1__box_6.setFont(font)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.s1__box_6.addItem("")
        self.open_button = QtWidgets.QPushButton(self.formGroupBox1)
        self.open_button.setGeometry(QtCore.QRect(11, 174, 100, 25))
        self.open_button.setMinimumSize(QtCore.QSize(100, 25))
        self.open_button.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.open_button.setFont(font)
        self.open_button.setObjectName("open_button")
        self.close_button = QtWidgets.QPushButton(self.formGroupBox1)
        self.close_button.setGeometry(QtCore.QRect(118, 174, 100, 25))
        self.close_button.setMinimumSize(QtCore.QSize(100, 25))
        self.close_button.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.state_label = QtWidgets.QLabel(self.formGroupBox1)
        self.state_label.setGeometry(QtCore.QRect(11, 68, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.state_label.setFont(font)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.gridLayout.addWidget(self.formGroupBox1, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.result_lb = QtWidgets.QLabel(self.groupBox_4)
        self.result_lb.setEnabled(True)
        self.result_lb.setMinimumSize(QtCore.QSize(100, 140))
        self.result_lb.setMaximumSize(QtCore.QSize(100, 140))
        self.result_lb.setStyleSheet("font: 16pt \"Adobe Devanagari\";")
        self.result_lb.setWordWrap(True)
        self.result_lb.setObjectName("result_lb")
        self.gridLayout_8.addWidget(self.result_lb, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.start_test_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.start_test_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.start_test_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.start_test_bt.setFont(font)
        self.start_test_bt.setObjectName("start_test_bt")
        self.gridLayout_10.addWidget(self.start_test_bt, 3, 0, 1, 1)
        self.stop_test_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.stop_test_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.stop_test_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.stop_test_bt.setFont(font)
        self.stop_test_bt.setObjectName("stop_test_bt")
        self.gridLayout_10.addWidget(self.stop_test_bt, 2, 0, 1, 1)
        self.one_test_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.one_test_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.one_test_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.one_test_bt.setFont(font)
        self.one_test_bt.setObjectName("one_test_bt")
        self.gridLayout_10.addWidget(self.one_test_bt, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 1, 4, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.sta_recv_rssi_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.sta_recv_rssi_le.setMinimumSize(QtCore.QSize(61, 20))
        self.sta_recv_rssi_le.setMaximumSize(QtCore.QSize(61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sta_recv_rssi_le.setFont(font)
        self.sta_recv_rssi_le.setObjectName("sta_recv_rssi_le")
        self.gridLayout_7.addWidget(self.sta_recv_rssi_le, 0, 1, 1, 1)
        self.test_times_lb_4 = QtWidgets.QLabel(self.groupBox_3)
        self.test_times_lb_4.setMinimumSize(QtCore.QSize(80, 20))
        self.test_times_lb_4.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.test_times_lb_4.setFont(font)
        self.test_times_lb_4.setObjectName("test_times_lb_4")
        self.gridLayout_7.addWidget(self.test_times_lb_4, 2, 0, 1, 1)
        self.send_num_lb = QtWidgets.QLabel(self.groupBox_3)
        self.send_num_lb.setMinimumSize(QtCore.QSize(80, 20))
        self.send_num_lb.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.send_num_lb.setFont(font)
        self.send_num_lb.setObjectName("send_num_lb")
        self.gridLayout_7.addWidget(self.send_num_lb, 0, 0, 1, 1)
        self.meter_addr_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.meter_addr_le.setMinimumSize(QtCore.QSize(110, 20))
        self.meter_addr_le.setMaximumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.meter_addr_le.setFont(font)
        self.meter_addr_le.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.meter_addr_le.setText("")
        self.meter_addr_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meter_addr_le.setObjectName("meter_addr_le")
        self.gridLayout_7.addWidget(self.meter_addr_le, 2, 1, 1, 1)
        self.test_times_lb_3 = QtWidgets.QLabel(self.groupBox_3)
        self.test_times_lb_3.setMinimumSize(QtCore.QSize(80, 20))
        self.test_times_lb_3.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.test_times_lb_3.setFont(font)
        self.test_times_lb_3.setObjectName("test_times_lb_3")
        self.gridLayout_7.addWidget(self.test_times_lb_3, 1, 0, 1, 1)
        self.sta_send_rssi_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.sta_send_rssi_le.setMinimumSize(QtCore.QSize(61, 20))
        self.sta_send_rssi_le.setMaximumSize(QtCore.QSize(61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sta_send_rssi_le.setFont(font)
        self.sta_send_rssi_le.setObjectName("sta_send_rssi_le")
        self.gridLayout_7.addWidget(self.sta_send_rssi_le, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pass_cnt_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.pass_cnt_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.pass_cnt_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pass_cnt_bt.setFont(font)
        self.pass_cnt_bt.setStyleSheet("color: rgb(85, 170, 0);\n"
"font: 75 14pt \"Adobe Devanagari\";")
        self.pass_cnt_bt.setObjectName("pass_cnt_bt")
        self.gridLayout_9.addWidget(self.pass_cnt_bt, 0, 0, 1, 1)
        self.fail_cnt_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.fail_cnt_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.fail_cnt_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.fail_cnt_bt.setFont(font)
        self.fail_cnt_bt.setMouseTracking(False)
        self.fail_cnt_bt.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Adobe Devanagari\";")
        self.fail_cnt_bt.setObjectName("fail_cnt_bt")
        self.gridLayout_9.addWidget(self.fail_cnt_bt, 0, 1, 1, 1)
        self.clear_bt = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.clear_bt.setMinimumSize(QtCore.QSize(70, 40))
        self.clear_bt.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.clear_bt.setFont(font)
        self.clear_bt.setObjectName("clear_bt")
        self.gridLayout_9.addWidget(self.clear_bt, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 3, 1, 2)
        self.testcase_tv = QtWidgets.QTableView(self.stackedWidgetPage1)
        self.testcase_tv.setMinimumSize(QtCore.QSize(280, 180))
        self.testcase_tv.setObjectName("testcase_tv")
        self.gridLayout_13.addWidget(self.testcase_tv, 1, 1, 1, 3)
        self.history_tv = QtWidgets.QTableView(self.stackedWidgetPage1)
        self.history_tv.setMinimumSize(QtCore.QSize(230, 180))
        self.history_tv.setObjectName("history_tv")
        self.gridLayout_13.addWidget(self.history_tv, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox.setMinimumSize(QtCore.QSize(228, 91))
        self.groupBox.setMaximumSize(QtCore.QSize(228, 91))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.channel_num_lb = QtWidgets.QLabel(self.groupBox)
        self.channel_num_lb.setMinimumSize(QtCore.QSize(100, 20))
        self.channel_num_lb.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.channel_num_lb.setFont(font)
        self.channel_num_lb.setObjectName("channel_num_lb")
        self.gridLayout_2.addWidget(self.channel_num_lb, 0, 0, 1, 1)
        self.channel_num_Box = QtWidgets.QComboBox(self.groupBox)
        self.channel_num_Box.setMinimumSize(QtCore.QSize(100, 20))
        self.channel_num_Box.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.channel_num_Box.setFont(font)
        self.channel_num_Box.setObjectName("channel_num_Box")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.channel_num_Box.addItem("")
        self.gridLayout_2.addWidget(self.channel_num_Box, 0, 1, 1, 1)
        self.power_lb = QtWidgets.QLabel(self.groupBox)
        self.power_lb.setMinimumSize(QtCore.QSize(100, 20))
        self.power_lb.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.power_lb.setFont(font)
        self.power_lb.setObjectName("power_lb")
        self.gridLayout_2.addWidget(self.power_lb, 1, 0, 1, 1)
        self.dB_Box = QtWidgets.QComboBox(self.groupBox)
        self.dB_Box.setMinimumSize(QtCore.QSize(100, 20))
        self.dB_Box.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dB_Box.setFont(font)
        self.dB_Box.setObjectName("dB_Box")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.dB_Box.addItem("")
        self.gridLayout_2.addWidget(self.dB_Box, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_2.setMinimumSize(QtCore.QSize(228, 91))
        self.groupBox_2.setMaximumSize(QtCore.QSize(228, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 208, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.test_times_lb = QtWidgets.QLabel(self.layoutWidget)
        self.test_times_lb.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.test_times_lb.setFont(font)
        self.test_times_lb.setObjectName("test_times_lb")
        self.gridLayout_3.addWidget(self.test_times_lb, 0, 0, 1, 1)
        self.test_times_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.test_times_le.setMinimumSize(QtCore.QSize(100, 20))
        self.test_times_le.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.test_times_le.setFont(font)
        self.test_times_le.setObjectName("test_times_le")
        self.gridLayout_3.addWidget(self.test_times_le, 0, 1, 1, 1)
        self.timing_lb = QtWidgets.QLabel(self.layoutWidget)
        self.timing_lb.setMinimumSize(QtCore.QSize(100, 20))
        self.timing_lb.setMaximumSize(QtCore.QSize(82, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timing_lb.setFont(font)
        self.timing_lb.setObjectName("timing_lb")
        self.gridLayout_3.addWidget(self.timing_lb, 1, 0, 1, 1)
        self.timing_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.timing_le.setMinimumSize(QtCore.QSize(100, 20))
        self.timing_le.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timing_le.setFont(font)
        self.timing_le.setObjectName("timing_le")
        self.gridLayout_3.addWidget(self.timing_le, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem4, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Gadget)
        QtCore.QMetaObject.connectSlotsByName(Gadget)

    def retranslateUi(self, Gadget):
        _translate = QtCore.QCoreApplication.translate
        Gadget.setWindowTitle(_translate("Gadget", "Form"))
        self.formGroupBox1.setTitle(_translate("Gadget", "串口设置"))
        self.s1__lb_1.setText(_translate("Gadget", "扫描串口"))
        self.s1__box_1.setText(_translate("Gadget", "Detection Port"))
        self.s1__lb_2.setText(_translate("Gadget", "选择串口"))
        self.s1__lb_3.setText(_translate("Gadget", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Gadget", "9600"))
        self.s1__box_3.setItemText(1, _translate("Gadget", "115200"))
        self.s1__box_3.setItemText(2, _translate("Gadget", "2400"))
        self.s1__box_3.setItemText(3, _translate("Gadget", "4800"))
        self.s1__box_3.setItemText(4, _translate("Gadget", "14400"))
        self.s1__box_3.setItemText(5, _translate("Gadget", "19200"))
        self.s1__box_3.setItemText(6, _translate("Gadget", "38400"))
        self.s1__box_3.setItemText(7, _translate("Gadget", "57600"))
        self.s1__box_3.setItemText(8, _translate("Gadget", "76800"))
        self.s1__box_3.setItemText(9, _translate("Gadget", "12800"))
        self.s1__box_3.setItemText(10, _translate("Gadget", "230400"))
        self.s1__box_3.setItemText(11, _translate("Gadget", "460800"))
        self.s1__box_3.setItemText(12, _translate("Gadget", "3000000"))
        self.s1__lb_4.setText(_translate("Gadget", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Gadget", "8"))
        self.s1__box_4.setItemText(1, _translate("Gadget", "7"))
        self.s1__box_4.setItemText(2, _translate("Gadget", "6"))
        self.s1__box_4.setItemText(3, _translate("Gadget", "5"))
        self.s1__lb_5.setText(_translate("Gadget", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Gadget", "E"))
        self.s1__box_5.setItemText(1, _translate("Gadget", "O"))
        self.s1__box_5.setItemText(2, _translate("Gadget", "N"))
        self.s1__box_5.setItemText(3, _translate("Gadget", "M"))
        self.s1__box_5.setItemText(4, _translate("Gadget", "S"))
        self.s1__lb_6.setText(_translate("Gadget", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Gadget", "1"))
        self.s1__box_6.setItemText(1, _translate("Gadget", "2"))
        self.open_button.setText(_translate("Gadget", "打开"))
        self.close_button.setText(_translate("Gadget", "关闭"))
        self.groupBox_4.setTitle(_translate("Gadget", "测试"))
        self.result_lb.setText(_translate("Gadget", "等待测试..."))
        self.start_test_bt.setText(_translate("Gadget", "开始测试"))
        self.stop_test_bt.setText(_translate("Gadget", "停止测试"))
        self.one_test_bt.setText(_translate("Gadget", "单次测试"))
        self.groupBox_3.setTitle(_translate("Gadget", "阈值设置："))
        self.sta_recv_rssi_le.setText(_translate("Gadget", "55"))
        self.test_times_lb_4.setText(_translate("Gadget", "电表号"))
        self.send_num_lb.setText(_translate("Gadget", "STA接收Rssi"))
        self.test_times_lb_3.setText(_translate("Gadget", "STA发送Rssi"))
        self.sta_send_rssi_le.setText(_translate("Gadget", "55"))
        self.pass_cnt_bt.setText(_translate("Gadget", "0通过"))
        self.fail_cnt_bt.setText(_translate("Gadget", "0失败"))
        self.clear_bt.setText(_translate("Gadget", "清空"))
        self.groupBox.setTitle(_translate("Gadget", "发送参数配置"))
        self.channel_num_lb.setText(_translate("Gadget", "信道号"))
        self.channel_num_Box.setItemText(0, _translate("Gadget", "0"))
        self.channel_num_Box.setItemText(1, _translate("Gadget", "1"))
        self.channel_num_Box.setItemText(2, _translate("Gadget", "2"))
        self.channel_num_Box.setItemText(3, _translate("Gadget", "3"))
        self.channel_num_Box.setItemText(4, _translate("Gadget", "4"))
        self.channel_num_Box.setItemText(5, _translate("Gadget", "5"))
        self.channel_num_Box.setItemText(6, _translate("Gadget", "6"))
        self.channel_num_Box.setItemText(7, _translate("Gadget", "7"))
        self.channel_num_Box.setItemText(8, _translate("Gadget", "8"))
        self.channel_num_Box.setItemText(9, _translate("Gadget", "9"))
        self.channel_num_Box.setItemText(10, _translate("Gadget", "10"))
        self.channel_num_Box.setItemText(11, _translate("Gadget", "11"))
        self.channel_num_Box.setItemText(12, _translate("Gadget", "12"))
        self.channel_num_Box.setItemText(13, _translate("Gadget", "13"))
        self.channel_num_Box.setItemText(14, _translate("Gadget", "14"))
        self.channel_num_Box.setItemText(15, _translate("Gadget", "15"))
        self.channel_num_Box.setItemText(16, _translate("Gadget", "16"))
        self.channel_num_Box.setItemText(17, _translate("Gadget", "17"))
        self.channel_num_Box.setItemText(18, _translate("Gadget", "18"))
        self.channel_num_Box.setItemText(19, _translate("Gadget", "19"))
        self.channel_num_Box.setItemText(20, _translate("Gadget", "20"))
        self.channel_num_Box.setItemText(21, _translate("Gadget", "21"))
        self.channel_num_Box.setItemText(22, _translate("Gadget", "22"))
        self.channel_num_Box.setItemText(23, _translate("Gadget", "23"))
        self.channel_num_Box.setItemText(24, _translate("Gadget", "24"))
        self.channel_num_Box.setItemText(25, _translate("Gadget", "25"))
        self.channel_num_Box.setItemText(26, _translate("Gadget", "26"))
        self.channel_num_Box.setItemText(27, _translate("Gadget", "27"))
        self.channel_num_Box.setItemText(28, _translate("Gadget", "28"))
        self.channel_num_Box.setItemText(29, _translate("Gadget", "29"))
        self.channel_num_Box.setItemText(30, _translate("Gadget", "30"))
        self.channel_num_Box.setItemText(31, _translate("Gadget", "31"))
        self.channel_num_Box.setItemText(32, _translate("Gadget", "32"))
        self.channel_num_Box.setItemText(33, _translate("Gadget", "33"))
        self.channel_num_Box.setItemText(34, _translate("Gadget", "34"))
        self.channel_num_Box.setItemText(35, _translate("Gadget", "35"))
        self.channel_num_Box.setItemText(36, _translate("Gadget", "36"))
        self.channel_num_Box.setItemText(37, _translate("Gadget", "37"))
        self.channel_num_Box.setItemText(38, _translate("Gadget", "38"))
        self.channel_num_Box.setItemText(39, _translate("Gadget", "39"))
        self.channel_num_Box.setItemText(40, _translate("Gadget", "40"))
        self.channel_num_Box.setItemText(41, _translate("Gadget", "41"))
        self.channel_num_Box.setItemText(42, _translate("Gadget", "42"))
        self.channel_num_Box.setItemText(43, _translate("Gadget", "43"))
        self.channel_num_Box.setItemText(44, _translate("Gadget", "44"))
        self.channel_num_Box.setItemText(45, _translate("Gadget", "45"))
        self.channel_num_Box.setItemText(46, _translate("Gadget", "46"))
        self.channel_num_Box.setItemText(47, _translate("Gadget", "47"))
        self.channel_num_Box.setItemText(48, _translate("Gadget", "48"))
        self.channel_num_Box.setItemText(49, _translate("Gadget", "49"))
        self.channel_num_Box.setItemText(50, _translate("Gadget", "50"))
        self.channel_num_Box.setItemText(51, _translate("Gadget", "51"))
        self.channel_num_Box.setItemText(52, _translate("Gadget", "52"))
        self.channel_num_Box.setItemText(53, _translate("Gadget", "53"))
        self.channel_num_Box.setItemText(54, _translate("Gadget", "54"))
        self.channel_num_Box.setItemText(55, _translate("Gadget", "55"))
        self.channel_num_Box.setItemText(56, _translate("Gadget", "56"))
        self.channel_num_Box.setItemText(57, _translate("Gadget", "57"))
        self.channel_num_Box.setItemText(58, _translate("Gadget", "58"))
        self.channel_num_Box.setItemText(59, _translate("Gadget", "59"))
        self.channel_num_Box.setItemText(60, _translate("Gadget", "60"))
        self.channel_num_Box.setItemText(61, _translate("Gadget", "61"))
        self.channel_num_Box.setItemText(62, _translate("Gadget", "62"))
        self.channel_num_Box.setItemText(63, _translate("Gadget", "63"))
        self.channel_num_Box.setItemText(64, _translate("Gadget", "64"))
        self.power_lb.setText(_translate("Gadget", "发射功率"))
        self.dB_Box.setItemText(0, _translate("Gadget", "dB17"))
        self.dB_Box.setItemText(1, _translate("Gadget", "dB01"))
        self.dB_Box.setItemText(2, _translate("Gadget", "dB02"))
        self.dB_Box.setItemText(3, _translate("Gadget", "dB05"))
        self.dB_Box.setItemText(4, _translate("Gadget", "dB11"))
        self.dB_Box.setItemText(5, _translate("Gadget", "dB14"))
        self.dB_Box.setItemText(6, _translate("Gadget", "dB20"))
        self.groupBox_2.setTitle(_translate("Gadget", "循环配置"))
        self.test_times_lb.setText(_translate("Gadget", "循环测试次数"))
        self.test_times_le.setText(_translate("Gadget", "3"))
        self.timing_lb.setText(_translate("Gadget", "循环发送间隔(ms)"))
        self.timing_le.setText(_translate("Gadget", "0"))

